### ISSUE TITLE
在0.24.0版中Liff_size出現錯誤

### ISSUE THREAD

**Issue by jhang-jhe-wei** [etrex/kamiliff#3]
# 預期行為
## 開啟相對應尺寸的Liff分頁
1. 依照[kamigo套件](https://github.com/etrex/kamigo)指示建立todos
2. 開啟```app/views/todos/index.line.erb```修改第7行
```
 text "new", align: "end", action: uri_action(liff_path(path: new_todo_path)), color: "#0000ee"
```
變更為
```
 text "new", align: "end", action: uri_action(liff_path(path: new_todo_path, liff_size: :full)), color: "#0000ee"

```
3.  於line chatbot中輸入```todos```，並且按下Flex message右上方的```new```
# 目前行為
## 開啟後Liff後出現以下畫面

![](https://i.imgur.com/KIbGzCk.png)
# 原因
不清楚 : (
似乎跳轉2次...

**Comment by etrex** [comment]
### ruby 版本
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

### rails 版本
Rails 6.1.2.1

### 操作結果

照著操作
一切正常
無法重現問題

**Comment by etrex** [comment]
問題是來自於 LIFF 設定當中的 Scopes 沒有勾選 chat_message.write

![image](https://user-images.githubusercontent.com/563929/108061333-18973c00-7093-11eb-9954-3711f48634e8.png)

結案
