### ISSUE TITLE
0.24.1版無法使用liff_size切換不同size的LIFF

### ISSUE THREAD

**Issue by jhang-jhe-wei** [etrex/kamiliff#4]
# 版本
- mac os big sur 11.2.1
- Rails 6.1.2.1
- ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
- 其餘gem皆使用bundle update更新至最新

![](https://i.imgur.com/30aQrBT.png)

# 動作流程
1. 建立新的Login channel
2. 將Login channel切換成Published
3. 建立size為compact和tall的兩個LIFF分頁(除了名稱及size其他皆相同)
4. 建立rails專案
5. 新增.env
6. 新增```root to: "todos#index"```在```config/routes.rb```中
7. 新增js在```app/javascript/packs/application.js```中
8. 新增```config.hosts << "wells.tw"```在```config/application.rb``` 中
9. 啟動server```rails s```
10. 於line中輸入```/```
11.  點擊flex右上角```new```
12. 按下許可
13. 出現正常畫面
14.  修改```app/views/todos/index.line.erb```第七行為```text "new", align: "end", action: uri_action(liff_path(path: new_todo_path,liff_size: :tall)), color: "#0000ee"```
15. 重啟server
16. 於line中輸入```/```
17.  點擊flex右上角```new```
18. 出現錯誤
19. 按下返回鍵出現不存在的FULL size LIFF

----

## 1. 建立新的Login channel
![](https://i.imgur.com/PIfjUew.png)
## 2. 將Login channel切換成Published
![](https://i.imgur.com/io3Uaws.png) 
## 3. 建立size為compact和tall的兩個LIFF分頁(除了名稱及size其他皆相同)
![](https://i.imgur.com/obEL1HB.png)
![](https://i.imgur.com/BaR6RsN.png)
## 4. 建立rails專案
```
rails new demo
cd demo
bundle add kamigo
bundle add dotenv-rails
bundle update
rails g scaffold todo name desc
rails db:create
rails db:migrate
```
## 5. 新增.env
![](https://i.imgur.com/AHu6QGR.png)
## 6. 新增```root to: "todos#index"```在```config/routes.rb```中
![](https://i.imgur.com/hotNzvH.png)
## 7. 新增js在```app/javascript/packs/application.js```中
![](https://i.imgur.com/72QBsd8.png)
## 8. 新增```config.hosts << "wells.tw"```在```config/application.rb``` 中
![](https://i.imgur.com/5OUkFT6.png)
## 11.  點擊flex右上角```new```
![](https://i.imgur.com/zdL9HsG.png)
## 12. 按下許可
![](https://i.imgur.com/ov02iql.png)
## 13. 出現正常畫面
![](https://i.imgur.com/ajiBtCf.png)
## 14.  修改```app/views/todos/index.line.erb```第七行為```text "new", align: "end", action: uri_action(liff_path(path: new_todo_path,liff_size: :tall)), color: "#0000ee"```
![](https://i.imgur.com/pOFfBiK.png)
## 17.  點擊flex右上角```new```
![](https://i.imgur.com/AuFIui9.png)
## 18. 出現錯誤
![](https://i.imgur.com/TqNR3bX.png)
## 19. 按下返回鍵出現不存在的FULL size LIFF
![](https://i.imgur.com/VRwNRy6.png)

**Comment by etrex** [comment]
@jhang-jhe-wei 請確認 0.25.0 版本是否已解決問題

**Comment by etrex** [comment]
@jhang-jhe-wei 請確認 0.26.0 版本是否已解決問題
